stages:
  - build
  - test
  - generate_report
  - publish_report

variables:
  MAVEN_OPTS: "-Xms512m -Xmx2g"

cache:
  key: "$CI_COMMIT_REF_SLUG-maven"
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.8.6-openjdk-21
  script:
    - mvn install -Pskip-tests

test:
  stage: test
  image: maven:3.8.6-openjdk-21
  script:
    - mvn test -Dsurefire.suiteXmlFiles=API_Testing.xml -Dallure.results.directory=allure-results
  artifacts:
    paths:
      - allure-results
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    expire_in: 1 day

generate_report:
  stage: generate_report
  image: maven:3.8.6-openjdk-17
  script:
    - curl -L -o allure.zip https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip
    - unzip allure.zip -d allure
    - export PATH=$PATH:$(pwd)/allure/allure-commandline-2.13.9/bin
    - allure generate -c allure-results --clean -o _site
  artifacts:
    paths:
      - _site
    expire_in: 1 day

publish_report:
  stage: publish_report
  image: alpine:latest
  script:
    - apk add --no-cache curl
    - curl -X POST -F "file=@_site" -F "branch=$CI_COMMIT_REF_NAME" "https://pages.example.com/upload"  # Замените URL на ваш реальный адрес публикации
