name: API test (Advertisers + Admins + Offers)

on:
  schedule:
    - cron: '0 4 * * *'   
  workflow_dispatch:     

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven (skip tests)
      run: mvn install -Pskip-tests

    - name: Run tests
      run: mvn test -Dsurefire.suiteXmlFiles=API_Testing.xml -Dallure.results.directory=allure-results
      continue-on-error: true

    - name: Store allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results
        retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        curl -sLo allurectl https://github.com/allure-framework/allurectl/releases/latest/download/allurectl-linux
        chmod +x allurectl
        sudo mv allurectl /usr/local/bin/allurectl
        allurectl --version

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Generate Allure Report
      run: |
        allurectl generate allure-results -o _site --clean

    - name: Upload Allure Report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: _site
        path: _site
        retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish report

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
