name: API test v

on:
  schedule:
    - cron: '0 4 * * *'   
  workflow_dispatch:     

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Download Allure Results Artifact
        run: |
          ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/3snetTest/ThreeTracks/actions/artifacts?name=allure-results" | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") &&
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/3snetTest/ThreeTracks/actions/artifacts/$ARTIFACT_ID/zip" -o artifacts.zip &&
          mkdir -p allure-results && unzip artifacts.zip -d allure-results

  test:
    runs-on: ubuntu-latest
    needs: download-history
    steps:
      - name: Checkout code
        uses:
